apiVersion: v1
kind: Secret
metadata:
    name: db-encryption
    namespace: homarr
type: Opaque
stringData:
    db-encryption-key: ENC[AES256_GCM,data:E3drVoxOVJww089hLOJiulnYOMNloo7JLhu17wXJjY9/q+kazQEkjWmdr7PQycZzZAQqyzt1As+p0CQ6ci9lOQ==,iv:YSKuWeF3tt9TeFELFies+V4ae5gLAzujWL/tD2m1QTk=,tag:t+B14sRTV3olHhsmrY1uYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQlNCS2diU2p6K3pvbW1U
            UUcyTS9uWTJUdkp3a205cEJZVVpxQXJ0dzNzCnVRVWg5ZlZiWnlZUkJCaWh1b1pq
            eitOS2Vvb2RFK1N0UzVoWmxTMTNycm8KLS0tIHNxVTlaQjE0M0JQL2VvZnVZV2Za
            NDhwSzdqUUVBUFdtaHI1amhkUXRHVTAKD/nXI8LisxYamdGweGq5k6yRsUenrMy9
            5aWZ8iAezvbUtSyntroiRQTWJqCOP29QDRzTUupgT4Z0OYaqIjMNGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7w5hsptx9lcq0xe0n3tmgh0zx32f6yrx322t3hmxuf67f89dcnspd5rwx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T21:48:47Z"
    mac: ENC[AES256_GCM,data:nDGHarDWBpE3cPuLS4y1zx8dArg+Q4KgG6n7Nfmope2zXwa3W913u1EuL+WOPuBOvEBZfx9Wc7Auj57YTr1O+41I/Ws9Om41VpBT//mdOLZrQnsRN3l8xrc5RsCJmbTaA9Q1L9REbzYb+ZE7qqbsVPHXu8W6+JjiVrx1XDvY5Hg=,iv:fJtvR3EBpWUdEkezsj5itefEAb6ZQmIE3atVOTGZAxE=,tag:TPRPhkA0zVIWC/FoLc9TpA==,type:str]
    version: 3.13.3
