apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:h0hZWv5F4EgNOHhALNOEm7yNFBjoBrYAGpmeVyTddz6M/JmfhEsPiKCd2JXBMZal9VyNVpCAlhFgbxhcug+BK3+YC/JtjaG/7lEcHxsxnXtTlsaUmI9R3VgClYkSCy2x/HXRfi4r65uWqDtdsnKXaA28ZUqyjPFMDEJJDw16vKU4zDv1wkk9oGl3N0gL9LGQuzZG8h0igThpIlabB3vKnznb+zm9zPhM0oM1IGQe1o9RiyML0mBnA2bqcG4zwOfYUyelKlpJKZ7SDS822UxGrRYZAawbsat9TJqYSfKnoS/I/x7rqlYDwgHXNCY=,iv:cU9oLiH317E2JT+ESsV/oMiFciuEm+bzsUjnvZMrzTU=,tag:cPl/0O5VRYBClzinM7lyuQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: homelab-tunnel-credentials
    namespace: tunnel
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcTNSZHFGZ2NxelIrVUs2
            b0RHWGRvSnRMT2ZEOW9WZjA5MExFQi85Z2pFCmlUa2JVOXBlVDNSTHYwa1NGNm1O
            aEZmK3dqR0VlUzdLd0VyNXBOVFRnMzQKLS0tIEhlYkwxTkgrSXFLcElFTzBlMTZH
            cHJzRjhIZTh5TVh3REp1Z0RIQm5QVGsKGi9rqhgeOcTBZO2fn/9/hDYwf359tfoP
            mb6a06TE/CLvSmj3QO6S2qYxY6hS9o9xqlmKo/syEjVC8/hqCH1X8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7w5hsptx9lcq0xe0n3tmgh0zx32f6yrx322t3hmxuf67f89dcnspd5rwx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-11T21:30:19Z"
    mac: ENC[AES256_GCM,data:xq2TaFaoSwd4HRe8vXHbbWHEN3mtnmWnP8cJJETwYn3CkhKxLYo2h2rLSZIkYfae6I16kgFAk/5dJXEw8bkBYrd/Wt+wFpNniG+m5bkO2lWSt2+HX+tdxdN2jP5efpMtX/0uTnrvg/qBOsk1HlzovMkBUBu93qZ6lp9tumhx0GE=,iv:2YPu/UG63qftP5T8XAv61E7NZbw9RApVBsHHRPYSJqg=,tag:6ihO65FJ2H4p/4NtGBjkjw==,type:str]
    version: 3.13.3
