apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/rrstack/prowlarr
  claimRef:
    name: prowlarr-pvc
    namespace: rrstack
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-pvc
  namespace: rrstack
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
