apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/rrstack/prowlarr
  claimRef:
    name: prowlarr-pvc
    namespace: rrstack
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-pvc
  namespace: rrstack
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/rrstack/sabnzbd
  claimRef:
    name: sabnzbd-pvc
    namespace: rrstack
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-pvc
  namespace: rrstack
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: usenet-incomplete-pv
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/usenet/incomplete
  claimRef:
    name: usenet-incomplete-pvc
    namespace: rrstack
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: usenet-incomplete-pvc
  namespace: rrstack
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: usenet-complete-pv
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/usenet/complete
  claimRef:
    name: usenet-complete-pvc
    namespace: rrstack
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: usenet-complete-pvc
  namespace: rrstack
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
