apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: n8n
data:
  GENERIC_TIMEZONE: "America/Sao_Paulo"
  TZ: "America/Sao_Paulo"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true" 
  N8N_RUNNERS_ENABLED: "true"
  N8N_SECURE_COOKIE: "false" 
