apiVersion: v1
kind: Pod
metadata:
  name: n8n
  labels: 
    app: n8n
  namespace: n8n
spec:
  containers:
  - name: n8n
    image: n8nio/n8n:latest
    volumeMounts:
    - mountPath: /home/node/.n8n
      name: n8n-data
    ports:
      - name: n8n-port
        containerPort: 5678
        protocol: TCP
    envFrom:
    - configMapRef:
        name: config

  volumes:
    - name: n8n-data
      persistentVolumeClaim:
        claimName: n8n-claim

  securityContext:
    runAsUser: 1000
    #runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true


