apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-claim
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
