apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:vK8KSCpF3aVlmuuAqq5QkIoNclIiHvLEeXan0cs2h7OVYCxUlSDEK3r3YkJKpM4q1lo/JxUbFv9Rm3NYlYJZ9okvwz3eWFZ//80Izt7Fu2+SXTq9pPtFMErZSYI8N/hMoCj+bXxD1LN+7iC2Kbd1Ow1KoUXHTfhV6tY5coc3CdnYXF8PldsmdzRnwPEuUyRzpq36vwmpt195MUtXgGAzUr0fPpmspokf++nuTmJUef8YORlhI8vOfxMW658c5l1nHCYGAlcx365yaKutxFuvdFGPxnTqVSsCTiEWs+aopBgl8Bt/SRuVYmA94dk=,iv:XisjSPFtPPhE2z2k1ms3UvQB8dhbMKQCkwFzHrABdR8=,tag:rJH0dh0AAgnz3hSakDJDvQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: cloudflare
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKL3RWNUl2TnFZbk9LRG9P
            dkYxZmpBU3R1Q21JVzhwQVM2ZkZBZzcrOXh3ClI3d1I5RzB6VHdUNjJQaEgvVDNr
            UWN3RjlPN3ErY2hZdlFZc2J4Uk1Vc0kKLS0tIDN3dkZSUWF2M2dWRjZway9WU3Jo
            SGpUZVcxSGxRbWFhbXRDOVI1ck96ajQKmiTaorIOOyHQlI8cEB57n6kzUxbF+NAa
            mtt0doTkqHreb+OrrYI6AuFBU0bLfLuAh0wXjuqzMPGPadyST0MZ4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7w5hsptx9lcq0xe0n3tmgh0zx32f6yrx322t3hmxuf67f89dcnspd5rwx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T22:51:55Z"
    mac: ENC[AES256_GCM,data:+3bBTgg8gBiiLXkD+DSEG0zsRfGMxdlpyYUF0vIa00um945C8rzUv0cNaWwlUWPggN5bTFmiclYuJhjd9JTDCwhzY744wLiTwHwrHABGGCgJln3QBw5YireyNTrJtng5F0dJE09Zu71LKsafy6gFY6ysNCFINwKClu+appPRH4M=,iv:5K/sTs1t7WeEWELzileqSGfq5j3r0i5r3EkZHurWG6U=,tag:oFXbqxHNGJ42Tzy7knUbWg==,type:str]
    version: 3.13.3
