apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard
  namespace: adguard
spec:
  ingressClassName: traefik
  rules:
    - host: local.adguard.nicklab.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adguard-web
                port:
                  number: 3000
