apiVersion: v1
kind: Secret
metadata:
    name: linkding-container-env
type: Opaque
stringData:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:wr1xsw==,iv:pBE7BgY5WzH2lDU2BorwQaEQsD/1fZ4YPTmiLMXQD0Q=,tag:vmzRCdlQUCmy23J23BZFTQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:IC8gmgWSvHYkTn0=,iv:tYV6holu1SFJyP4wZp4dZ/IMlzD+toBG90pro4gOjoU=,tag:to4OIVvtSv8AbJ1kkVv6Uw==,type:str]
    LD_CSRF_TRUSTED_ORIGINS: ENC[AES256_GCM,data:hLUHVyoolPP3cLanRZ/N5050uUs3ZeTIUX78cQ==,iv:p5+WMSULY2fYGxATUCx7Fbzihz18uyRBWX36bHBAmI8=,tag:i9rT/dm6tdAou5bslZqmaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOVZOTDFtTkphQjgrWWNG
            L2doU3NiSHZFc0t6b0UzVEFQNE92aUR4aVRFCmNPQlJ2ZGdGTWdseHljN1JWdTdq
            SVNNaXJkK2pQdjdyWHpibkRNbFV2cDgKLS0tIG8vUm5xVGZwNmt4Y25sQ1ZLRU0z
            b1FTTGdSclNjTG1ERXNIMGNVSzlYM1UKwskML1yk6huyRrfczsi8ppwXIGDXDt0S
            ODTivit7YLlyKsHPLI9Ga3vP/47Lst2V24oqQsOrdI2CHx0tLS1Hrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7w5hsptx9lcq0xe0n3tmgh0zx32f6yrx322t3hmxuf67f89dcnspd5rwx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T12:09:29Z"
    mac: ENC[AES256_GCM,data:rk6qrod9lCVruKPObKscExnWSDDdc7qmPNyfLh1QirFLhhvTIvBRUorLifcafiJE4Apq07auUNtFBxLGLKXdJrMeRY20M1cQnCMCC0yCMABGIe3cRzU5sfeMufap0RcNFBe0UAJQZ0ebTwzZenIaZU8pDd8T7hIG5l054Jk6kGQ=,iv:NkeLWB1UZY+Q74yG+IofInvA+WfA6g5QgHsG7Af+6z4=,tag:ySSuE3A3QhzdpLbxNcV6Ww==,type:str]
    version: 3.13.3
