apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:lugp58PIPbk=,iv:IKOpynQT4WKrXUONRWVS7Bc4zZO9CU7zKmZtiXlzxqA=,tag:zt0Il5N5v/CPDTmhcmkAlA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:rsnTq4FctIjEZxkEObUDfg==,iv:jgj2/WK84FMIkCp1UO+qaN2lFpc0Mz/xS9FNMWMLoAA=,tag:2kd9wdSHZRcRWSLV7SKEqg==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ek5BZ3BmU1lrUTR2czRK
            eG1Da2J5aHBrWmF5MmliZVVHMG1VU3pMUTA0CktvSTM4d1JpVk16OUQ1eWkvTGZz
            ZGtQY2l3OEZGWTJHZHZmeDE5SXdPV3MKLS0tIGRkSlVGNFdBZkZFL0p1cWxYYUFx
            MnZoTlBwVEhDZGxOVjZwaCtsbzhTR2MKduJslPUdkOihKSfW9eIjOUdqj3/FSdfm
            At8syXNQsie7U2aEQw7pqYu2TEnAwXrUz0jDItYpFGOv8wtQ4r3lMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7w5hsptx9lcq0xe0n3tmgh0zx32f6yrx322t3hmxuf67f89dcnspd5rwx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T23:19:59Z"
    mac: ENC[AES256_GCM,data:IoV5tGx8j6pYCufp1l+CFjKYr55mLixg5Oe+YJcn7n4MYLi379HYdzPbvs3Tw7E7V+ryXZm1rk8gERZTEMSdcHR9+1R2ot9dv1RvjXiOH0sjySsDHLRa5aEjpRgDYrh5jhgEj610GEZeNfX2YHEJ6Og/8hYgbqU/MpGB4EYSK9c=,iv:RNFiuesjMBY7+uuRYe/AY6eF7Pedw1Sdo+jdfzg4dQ0=,tag:VaTKRVyWogNrI60/MkVmRw==,type:str]
    version: 3.13.3
