apiVersion: v1
data:
    password: ENC[AES256_GCM,data:axSjybfCZjc=,iv:dI50w/A7PzxB8GekKM23/tOz7NsbCHN4wXW1B5x0ZRs=,tag:ZGmDWUS/TYZmS50l/IkOqw==,type:str]
    user: ENC[AES256_GCM,data:xCDt+5Vo2fo=,iv:zpbnDUEXF3gil9z6/fAax/Sw8Y4mBE4wxBfEtwfN44Q=,tag:kf8VzjCvvlYkIpxI/xppIg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQ0FHTlkwUXVEOFI2MnBO
            VnREN3hDZHovWWo1VmJhMXhSYTBUNEVNYTBZCmIrazVYbS8yZjI3eEd5c2lZRHNz
            MWhpemYvcVZ4VFY4OHJRUXZFcEdtMUEKLS0tIDdHYkEvTFp3ZmFvOXlFaHVwQXdO
            OU15c0I4NWpBTDg3K21wMFdTS2tVb2cKg3rrFwdhH3DFyfBK6T2LKpa/Ae26ZYh6
            HjraaJC5/XmWH0MRs7bXnX+74BRLvnOMwKsUPT3KUBrhc865SvPjPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7w5hsptx9lcq0xe0n3tmgh0zx32f6yrx322t3hmxuf67f89dcnspd5rwx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T21:04:37Z"
    mac: ENC[AES256_GCM,data:tRFb9adBw6Cu761FhthIjM2GgSIl2dpWjY9YB5bvf/tBRpxf/wZDSBu5UrzFcZRJY/G5nr7mBsjq/S97Fz6BA29Tbc/OqWBvW8kv3+UYCIdbuD19qve5NasqH4w80fhccSakUJQ7Pp7o9UDDlW7kRrwcz0yyY0AzAUg/+QCXhvU=,iv:9ekDq96IVEeqCe5r0tjgGLCV6uugzTaAfyk/5EK8ZRw=,tag:d5chM+Z5TWjm6qoqJhIKTQ==,type:str]
    version: 3.13.3
