apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: beelink-master
          containers:
            - name: renovate
              image: renovate/renovate:latest
              args:
                - go-nick/homelab

              envFrom:
                - secretRef:
                    name: renovate-container-env
                - configMapRef:
                    name: renovate-configmap

              resources:
                requests:
                  cpu: "500m"
                  memory: "1.5Gi"
                limits:
                  cpu: "500m"
                  memory: "1.5Gi"

          restartPolicy: Never
