apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:Aedtc0/q2jJDahdLCQyZQrV8nPNB7vd5FVnE9mZdV0E38U0EkUTjiKvqOK1ZuLC9U8+U0PxrLGo=,iv:nLNWfgkOJwYMDAWlIj/h1hSzof4uReJRxB8daGK1VHc=,tag:Lo+8xdwGjKxhtKwgF/ddEQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: renovate-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpb2k3T0FJc1ZaUDVEUnFN
            cUxmMzRSNHVZYStSenU0NGFJRFc5YmdCNkhVClBsL2RuVTJ4UFB0VTJPWGU1RUhS
            c0VUMUhJa1BkMFlEbkdEbU1YaGJONVUKLS0tIFZ5RmppSmVqTzk0ME16eVc0RHhJ
            dEhhMDZKS0gwcEFRajBkT0NNcVV3SFEKeebymhelGJZ9ntkEpNt956QO7wfIHf0g
            UnaOmmtuLNBriEql1bwv9nETyYZqfnxqkSeDZNjpZIQPNn/uYggA5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7w5hsptx9lcq0xe0n3tmgh0zx32f6yrx322t3hmxuf67f89dcnspd5rwx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T18:14:10Z"
    mac: ENC[AES256_GCM,data:01uw8X6Wr0jcqFl5BtcDzhZ428KtYfLV2ApY6t5rQcPRiPOswotumaIqeP+R86o+lyN4VfYBdJsHs+wPEPKTxWd3c3jWKjcGdJbLKZ4tq2xYapOl2/OoROXci/fOOpbodFRrjC7wLibSnOU+3/O0eRxH7jJkW0ASMu1U3i0YiQA=,iv:knu7rw1+JAM52Z1BGzsQLQAxgRJ0kQ0gBK//uoEJA5k=,tag:HbsSuDTncd/qRKMdI8H1AQ==,type:str]
    version: 3.13.3
