apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:sTIM6Yw=,iv:WH/wqDLPhkp6X/YoGlF5Tb0YmC10qcz7qS2bNadmegQ=,tag:caa54UVotvHCsXZC26MMhw==,type:str]
    admin-password: ENC[AES256_GCM,data:HDodM45vvZTNVuM=,iv:sWsJ14kT1GnGGA5uaF8/A5FKLyaG2tqs57q0UhkzP+8=,tag:hEyMkcmLdVYyK3SFQLAcww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMFA1MitaM2RNRXN3VC9y
            NER6UmNnUkJoUTI1dGxzcVFtV1RXSU15Z2s4Cm9kVHRNSWYzdWx2eFVmVFdpZDI1
            NCtBd0lqODVYOWVEMzlqWUtnZnVWbXMKLS0tIEtHQTNWMkpuNlZVR0pmRjFRL3ZF
            enpRWmQ2WFFrMC9TaHI2dzNETWovVjQKs9R25IsIDxee/lHThvH60W64YhJKXrCL
            D6vwhOf1T/Yo3iUV7MmSccR7sY4R4y6eTYCO9eKZTcSS24g3bPp0og==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7w5hsptx9lcq0xe0n3tmgh0zx32f6yrx322t3hmxuf67f89dcnspd5rwx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T11:48:37Z"
    mac: ENC[AES256_GCM,data:0EoWvThEVKWOFm7ERP/Hh6DeSisZYxsir7Q0Wn5M9Vn1h1u0yuQIkyJMngiM6WAdrXB2/umPTxE+onaBXrcF/yP++wPp44MRv+6H4LNvTfhg0xt+KqTnQfKLirHyHICUDLIma02p/zIdPDA7FQlT+S9wUWnzUS59CKZOkLgWowU=,iv:L0TRjiVQS9CakTboVlbgmtjbdN7R68B/4WC/RYF6eA8=,tag:Pha7GEKReJLgnqcJoA4q2Q==,type:str]
    version: 3.13.3
