apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-tls-secret.yaml
configMapGenerator:
  - name: grafana-dashboard-namespace-overview
    namespace: monitoring
    files:
      - namespace-overview.json=dashboards/namespace-overview.json
    options: 
      labels:
        grafana_dashboard: "1"
      disableNameSuffixHash: true
